export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const INCREASE_PRODUCT_COUNT = "INCREASE_PRODUCT_COUNT";
export const DECREASE_PRODUCT_COUNT = "DECREASE_PRODUCT_COUNT";
export const CLEAR_CART = "CLEAR_CART";
export const REPLACE_CART_ITEMS = "REPLACE_CART_ITEMS";
